/**
 * Centralized constants for lead sources, statuses, and other dropdown options
 * to ensure consistency across all components
 */

export const LEAD_SOURCES = [
  { id: "website", name: "Website" },
  { id: "referral", name: "Referral" },
  { id: "social_media", name: "Social Media" },
  { id: "email_campaign", name: "Email Campaign" },
  { id: "event", name: "Event" },
  { id: "paid_search", name: "Paid Search" },
  { id: "organic_search", name: "Organic Search" },
  { id: "direct", name: "Direct" },
  { id: "trade_show", name: "Trade Show" },
  { id: "webinar", name: "Webinar" },
  { id: "cold_call", name: "Cold Call" },
  { id: "partner", name: "Partner" },
  { id: "advertisement", name: "Advertisement" },
  { id: "content_marketing", name: "Content Marketing" },
  { id: "other", name: "Other" },
  { id: "import", name: "Import" },
  { id: "manual", name: "Manual Entry" },
  { id: "all_sources", name: "All Sources" },
] as const;

export const LEAD_STATUSES = [
  { id: "new", name: "New" },
  { id: "contacted", name: "Contacted" },
  { id: "qualified", name: "Qualified" },
  { id: "proposal", name: "Proposal" },
  { id: "negotiation", name: "Negotiation" },
  { id: "won", name: "Won" },
  { id: "lost", name: "Lost" },
  { id: "all_statuses", name: "All Statuses" },
] as const;

export const CONTACT_TYPES = [
  { id: "business", name: "Business" },
  { id: "individual", name: "Individual" },
] as const;

export const LIFECYCLE_STAGES = [
  { id: "lead", name: "Lead" },
  { id: "opportunity", name: "Opportunity" },
  { id: "customer", name: "Customer" },
  { id: "evangelist", name: "Evangelist" },
  { id: "churned", name: "Churned" },
] as const;

export const LEGAL_BASES = [
  { id: "consent", name: "Consent" },
  { id: "contract", name: "Contract" },
  { id: "legitimate_interest", name: "Legitimate Interest" },
  { id: "legal_obligation", name: "Legal Obligation" },
] as const;

export const COUNTRIES = [
  { id: "us", name: "United States" },
  { id: "ca", name: "Canada" },
  { id: "uk", name: "United Kingdom" },
  { id: "au", name: "Australia" },
  { id: "fr", name: "France" },
  { id: "de", name: "Germany" },
  { id: "jp", name: "Japan" },
  { id: "other", name: "Other" },
] as const;

export const INDUSTRIES = [
  { id: "Accounting", name: "Accounting" },
  { id: "Airlines/Aviation", name: "Airlines/Aviation" },
  { id: "Alternative Dispute Resolution", name: "Alternative Dispute Resolution" },
  { id: "Alternative Medicine", name: "Alternative Medicine" },
  { id: "Animation", name: "Animation" },
  { id: "Apparel & Fashion", name: "Apparel & Fashion" },
  { id: "Architecture & Planning", name: "Architecture & Planning" },
  { id: "Arts and Crafts", name: "Arts and Crafts" },
  { id: "Automotive", name: "Automotive" },
  { id: "Aviation & Aerospace", name: "Aviation & Aerospace" },
  { id: "Banking", name: "Banking" },
  { id: "Biotechnology", name: "Biotechnology" },
  { id: "Broadcast Media", name: "Broadcast Media" },
  { id: "Building Materials", name: "Building Materials" },
  { id: "Business Supplies and Equipment", name: "Business Supplies and Equipment" },
  { id: "Capital Markets", name: "Capital Markets" },
  { id: "Chemicals", name: "Chemicals" },
  { id: "Civic & Social Organization", name: "Civic & Social Organization" },
  { id: "Civil Engineering", name: "Civil Engineering" },
  { id: "Commercial Real Estate", name: "Commercial Real Estate" },
  { id: "Computer & Network Security", name: "Computer & Network Security" },
  { id: "Computer Games", name: "Computer Games" },
  { id: "Computer Hardware", name: "Computer Hardware" },
  { id: "Computer Networking", name: "Computer Networking" },
  { id: "Computer Software", name: "Computer Software" },
  { id: "Internet", name: "Internet" },
  { id: "Construction", name: "Construction" },
  { id: "Consumer Electronics", name: "Consumer Electronics" },
  { id: "Consumer Goods", name: "Consumer Goods" },
  { id: "Consumer Services", name: "Consumer Services" },
  { id: "Cosmetics", name: "Cosmetics" },
  { id: "Dairy", name: "Dairy" },
  { id: "Defense & Space", name: "Defense & Space" },
  { id: "Design", name: "Design" },
  { id: "Education Management", name: "Education Management" },
  { id: "E-Learning", name: "E-Learning" },
  { id: "Electrical/Electronic Manufacturing", name: "Electrical/Electronic Manufacturing" },
  { id: "Entertainment", name: "Entertainment" },
  { id: "Environmental Services", name: "Environmental Services" },
  { id: "Events Services", name: "Events Services" },
  { id: "Executive Office", name: "Executive Office" },
  { id: "Facilities Services", name: "Facilities Services" },
  { id: "Farming", name: "Farming" },
  { id: "Financial Services", name: "Financial Services" },
  { id: "Fine Art", name: "Fine Art" },
  { id: "Fishery", name: "Fishery" },
  { id: "Food & Beverages", name: "Food & Beverages" },
  { id: "Food Production", name: "Food Production" },
  { id: "Fund-Raising", name: "Fund-Raising" },
  { id: "Furniture", name: "Furniture" },
  { id: "Gambling & Casinos", name: "Gambling & Casinos" },
  { id: "Glass, Ceramics & Concrete", name: "Glass, Ceramics & Concrete" },
  { id: "Government Administration", name: "Government Administration" },
  { id: "Government Relations", name: "Government Relations" },
  { id: "Graphic Design", name: "Graphic Design" },
  { id: "Health, Wellness and Fitness", name: "Health, Wellness and Fitness" },
  { id: "Higher Education", name: "Higher Education" },
  { id: "Hospital & Health Care", name: "Hospital & Health Care" },
  { id: "Hospitality", name: "Hospitality" },
  { id: "Human Resources", name: "Human Resources" },
  { id: "Import and Export", name: "Import and Export" },
  { id: "Individual & Family Services", name: "Individual & Family Services" },
  { id: "Industrial Automation", name: "Industrial Automation" },
  { id: "Information Services", name: "Information Services" },
  { id: "Information Technology and Services", name: "Information Technology and Services" },
  { id: "Insurance", name: "Insurance" },
  { id: "International Affairs", name: "International Affairs" },
  { id: "International Trade and Development", name: "International Trade and Development" },
  { id: "Investment Banking", name: "Investment Banking" },
  { id: "Investment Management", name: "Investment Management" },
  { id: "Judiciary", name: "Judiciary" },
  { id: "Law Enforcement", name: "Law Enforcement" },
  { id: "Law Practice", name: "Law Practice" },
  { id: "Legal Services", name: "Legal Services" },
  { id: "Legislative Office", name: "Legislative Office" },
  { id: "Leisure, Travel & Tourism", name: "Leisure, Travel & Tourism" },
  { id: "Libraries", name: "Libraries" },
  { id: "Logistics and Supply Chain", name: "Logistics and Supply Chain" },
  { id: "Luxury Goods & Jewelry", name: "Luxury Goods & Jewelry" },
  { id: "Machinery", name: "Machinery" },
  { id: "Management Consulting", name: "Management Consulting" },
  { id: "Maritime", name: "Maritime" },
  { id: "Market Research", name: "Market Research" },
  { id: "Marketing and Advertising", name: "Marketing and Advertising" },
  { id: "Mechanical or Industrial Engineering", name: "Mechanical or Industrial Engineering" },
  { id: "Media Production", name: "Media Production" },
  { id: "Medical Devices", name: "Medical Devices" },
  { id: "Medical Practice", name: "Medical Practice" },
  { id: "Mental Health Care", name: "Mental Health Care" },
  { id: "Military", name: "Military" },
  { id: "Mining & Metals", name: "Mining & Metals" },
  { id: "Motion Pictures and Film", name: "Motion Pictures and Film" },
  { id: "Museums and Institutions", name: "Museums and Institutions" },
  { id: "Music", name: "Music" },
  { id: "Nanotechnology", name: "Nanotechnology" },
  { id: "Newspapers", name: "Newspapers" },
  { id: "Non-Profit Organization Management", name: "Non-Profit Organization Management" },
  { id: "Oil & Energy", name: "Oil & Energy" },
  { id: "Online Media", name: "Online Media" },
  { id: "Outsourcing/Offshoring", name: "Outsourcing/Offshoring" },
  { id: "Package/Freight Delivery", name: "Package/Freight Delivery" },
  { id: "Packaging and Containers", name: "Packaging and Containers" },
  { id: "Paper & Forest Products", name: "Paper & Forest Products" },
  { id: "Performing Arts", name: "Performing Arts" },
  { id: "Pharmaceuticals", name: "Pharmaceuticals" },
  { id: "Philanthropy", name: "Philanthropy" },
  { id: "Photography", name: "Photography" },
  { id: "Plastics", name: "Plastics" },
  { id: "Political Organization", name: "Political Organization" },
  { id: "Primary/Secondary Education", name: "Primary/Secondary Education" },
  { id: "Printing", name: "Printing" },
  { id: "Professional Training & Coaching", name: "Professional Training & Coaching" },
  { id: "Program Development", name: "Program Development" },
  { id: "Public Policy", name: "Public Policy" },
  { id: "Public Relations and Communications", name: "Public Relations and Communications" },
  { id: "Public Safety", name: "Public Safety" },
  { id: "Publishing", name: "Publishing" },
  { id: "Railroad Manufacture", name: "Railroad Manufacture" },
  { id: "Ranching", name: "Ranching" },
  { id: "Real Estate", name: "Real Estate" },
  { id: "Recreational Facilities and Services", name: "Recreational Facilities and Services" },
  { id: "Religious Institutions", name: "Religious Institutions" },
  { id: "Renewables & Environment", name: "Renewables & Environment" },
  { id: "Research", name: "Research" },
  { id: "Restaurants", name: "Restaurants" },
  { id: "Retail", name: "Retail" },
  { id: "Security and Investigations", name: "Security and Investigations" },
  { id: "Semiconductors", name: "Semiconductors" },
  { id: "Shipbuilding", name: "Shipbuilding" },
  { id: "Sporting Goods", name: "Sporting Goods" },
  { id: "Sports", name: "Sports" },
  { id: "Staffing and Recruiting", name: "Staffing and Recruiting" },
  { id: "Supermarkets", name: "Supermarkets" },
  { id: "Telecommunications", name: "Telecommunications" },
  { id: "Textiles", name: "Textiles" },
  { id: "Think Tanks", name: "Think Tanks" },
  { id: "Tobacco", name: "Tobacco" },
  { id: "Translation and Localization", name: "Translation and Localization" },
  { id: "Transportation/Trucking/Railroad", name: "Transportation/Trucking/Railroad" },
  { id: "Utilities", name: "Utilities" },
  { id: "Venture Capital & Private Equity", name: "Venture Capital & Private Equity" },
  { id: "Veterinary", name: "Veterinary" },
  { id: "Warehousing", name: "Warehousing" },
  { id: "Wholesale", name: "Wholesale" },
  { id: "Wine and Spirits", name: "Wine and Spirits" },
  { id: "Wireless", name: "Wireless" },
  { id: "Writing and Editing", name: "Writing and Editing" },
] as const;

// Legacy industry suggestions for backward compatibility
export const INDUSTRY_SUGGESTIONS = INDUSTRIES.map(i => i.name);

// Type exports for TypeScript
export type LeadSource = typeof LEAD_SOURCES[number]['id'];
export type LeadStatus = typeof LEAD_STATUSES[number]['id'];
export type ContactType = typeof CONTACT_TYPES[number]['id'];
export type LifecycleStage = typeof LIFECYCLE_STAGES[number]['id'];
export type LegalBasis = typeof LEGAL_BASES[number]['id'];
export type Country = typeof COUNTRIES[number]['id'];